### ISSUE TITLE
Staking offline, stops processing blocks

### ISSUE THREAD

**Issue by zjeraar** [AuroraDAO/aurad#1]
I experienced twice that the daemon stopped processing blocks and just kept outputting `STAKING OFFLINE: Your staker is out of sync with the blockchain`. Both times was after it was running okay and online.

**Comment by bradennapier** [comment]
Yes, we are aware of this issue currently and are looking into it as a high priority.  The connection between the node and `aurad` stop communicating and a restart should resolve this. 

We are, in addition, working out ways to notify you when the node goes offline/online as well since you should not have to constantly check the status for worry of things like this.

**Comment by kokleong98** [comment]
I wrote below shell script to check aura logs in cron every 10 minutes to run update and restart it if detected offline more than 10 times. Hopes that help.

#!/bin/bash

test=$(aura logs | grep STAKING | tail -n 10 | grep OFFLINE -c)
echo $test
if [ $test -eq 10 ]
then
  aura stop
  npm install -g @auroradao/aurad-cli
  aura start
fi

**Comment by mexican1973** [comment]
How do i start it to run always in background?

**Comment by Ernestopheles** [comment]
aura: command not found
(script in home/.../script directory under the user where aura is running, crontab -e under this user also)

**Comment by kokleong98** [comment]
> aura: command not found
> (script in home/.../script directory under the user where aura is running, crontab -e under this user also)

Did you install everything following the official guide?
https://github.com/AuroraDAO/aurad
Mine working perfectly fine.
The aura cli is using node.js as I can see.

**Comment by Ernestopheles** [comment]
Not really, I did everything under root, from a certain point on I did the following under my user as there was an error if I did it under root.
I know that was not quiet correct, but as anything else seems to be running well I did not like to reinstall.

**Comment by Ernestopheles** [comment]
> > Not really, I started the installations under root, from a certain point on I did the following under my user as there was an error when I did it under root.
> > I know that was not quiet correct, but as anything else seems to be running well I did not like to reinstall.
> 
> Then my personal advise to you is to test which account have access to those aura command and setup cron job under those account. (^_^)

Well, the aura command does run under the user I am staking. Just crontab does not run this command (crontab -e).

**Comment by kokleong98** [comment]
> > > Not really, I started the installations under root, from a certain point on I did the following under my user as there was an error when I did it under root.
> > > I know that was not quiet correct, but as anything else seems to be running well I did not like to reinstall.
> > 
> > 
> > Then my personal advise to you is to test which account have access to those aura command and setup cron job under those account. (^_^)
> 
> Well, the aura command does run under the user I am staking. Just crontab does not run this command (crontab -e).

I'm out of ideas. Sorry can't help you. I'm experiment migrating my stake from 1 droplet to another. Probably working but I'm don't know how to verify it. Staking is ONLINE on the new droplet though.

**Comment by kokleong98** [comment]
I have put simple guide for setting up the simple cron monitor job.
https://github.com/kokleong98/aura-setup

**Comment by kokleong98** [comment]
Added script to install aura as systemd service and auto start on system reboot.
https://github.com/kokleong98/aura-setup/blob/master/aura-service-install.sh

**Comment by kokleong98** [comment]
> Added script to install aura as systemd service and auto start on system reboot.
> https://github.com/kokleong98/aura-setup/blob/master/aura-service-install.sh

I have updated the systemd service to perform similar functionality as cron monitor job.
Please remove your cron monitor job if you are using the latest systemd service.

**Comment by mgarciap** [comment]
Hi @bradennapier do you have an ETA for this issue?
I just deployed everything in Digitalocean (opened inbound port 8443). It took a very long time to write the trades. 
Now I get `Status: Your staker is out of sync with the blockchain`

```
aurad@idex-aurad:~$ aura status
aurad-cli v0.1.4
Latest version: v0.1.4
Cold wallet: 0x...
Staked AURA: ... AURA 
Total Staked AURA: 80913252.37 AURA
Staking: offline [Sat Apr 13 2019 14:11:25 GMT+0000 (Coordinated Universal Time)]
Status: Your staker is out of sync with the blockchain
Current period: Mon Apr 01 2019 12:00:00 GMT+0000 to Sun Apr 14 2019 11:59:59 GMT+0000
My Period Credits/Total Period Credits: 0.00 / 23950796 (0.00%)
Last period earnings: 0.000000 ETH
Last period credits: 0.00 / 20491449 (0.00%)
Earnings History: To access your complete earnings history, visit here: https://reporting.idex.market/aurad/earnings/9aaa5c3e87c65d80a671176de1dc88e9
Further Information: For further details on this information, please refer to the full documentation: https://github.com/AuroraDAO/aurad
```
```
Ubuntu 16.04.6 x64 
Docker version 18.09.5
Compose version 1.24.0
```
`$aura logs` output: https://gist.github.com/mgarciap/b783269c10f4bf626d2cfeaf98385284

**Comment by mgarciap** [comment]
> Hi @bradennapier do you have an ETA for this issue?
> I just deployed everything in Digitalocean (opened inbound port 8443). It took a very long time to write the trades.
> Now I get `Status: Your staker is out of sync with the blockchain`
> 
> ```
> aurad@idex-aurad:~$ aura status
> aurad-cli v0.1.4
> Latest version: v0.1.4
> Cold wallet: 0x...
> Staked AURA: ... AURA 
> Total Staked AURA: 80913252.37 AURA
> Staking: offline [Sat Apr 13 2019 14:11:25 GMT+0000 (Coordinated Universal Time)]
> Status: Your staker is out of sync with the blockchain
> Current period: Mon Apr 01 2019 12:00:00 GMT+0000 to Sun Apr 14 2019 11:59:59 GMT+0000
> My Period Credits/Total Period Credits: 0.00 / 23950796 (0.00%)
> Last period earnings: 0.000000 ETH
> Last period credits: 0.00 / 20491449 (0.00%)
> Earnings History: To access your complete earnings history, visit here: https://reporting.idex.market/aurad/earnings/9aaa5c3e87c65d80a671176de1dc88e9
> Further Information: For further details on this information, please refer to the full documentation: https://github.com/AuroraDAO/aurad
> ```
> ```
> Ubuntu 16.04.6 x64 
> Docker version 18.09.5
> Compose version 1.24.0
> ```
> `$aura logs` output: https://gist.github.com/mgarciap/b783269c10f4bf626d2cfeaf98385284

After one more day it seems that the staker got in sync with the blockchain and my node is online :)
UX might be improved.
