### ISSUE TITLE
Is it possible to use metamask wallet to do staking?

### ISSUE THREAD

**Issue by WhaleChen** [AuroraDAO/aurad#11]
Hi, I am really excited to see AuraDao staking. All is going well until  I try to use metamask address to do the staking. I do not know whether it is because it needs 7 days(I see the updated readme still wrote 3 days)  to stake or metamask address cannot be staked.Many 3x! 
`ERROR: Your cold wallet is not qualified for staking`

**Comment by Bobface** [comment]
The incubation period was disabled for the first 3 days after the launch. The 7 days incubation period is now active, so you either need to wait a little more or you do not have 10,000 AURA on your wallet.

**Comment by Troyjohns** [comment]
I am able to see my matured staked balance using metamask but can't figure out where to input the aurad signed message.  I need to do this to get my "sig" value.  Many thanks for any help you can give.

**Comment by yennieb** [comment]
Hi @Troyjohns, you can use this link to sign the message:
https://myetherwallet.com/signmsg.html

**Comment by sschueller** [comment]
Sign message is now here: https://myetherwallet.com/interface/sign-message
