### ISSUE TITLE
Something wrong with config process~ 

### ISSUE THREAD

**Issue by WhaleChen** [AuroraDAO/aurad#25]
I am running `aura config`  and the process going smoothly and I come across this problem. 
```
Wallet signature confirmed.
TypeError: this.utils.randomHex is not a function
    at Proxy.create (~/.nvm/versions/node/v10.15.0/lib/node_modules/@auroradao/aurad-cli/node_modules/web3-eth-accounts/dist/web3-eth-accounts.cjs.js:96:77)
    at ConfigCommand.run (~/.nvm/versions/node/v10.15.0/lib/node_modules/@auroradao/aurad-cli/src/commands/config.js:116:53) 
```
I do not know there is the problem of web3 or aura. 
I share the [link](https://github.com/ethereum/web3.js/issues/2238#issuecomment-458437517 ) here

**Comment by frakevich** [comment]
Running into the same issue. Looks like it has to do with package incompatibility.  I tried downgrading web3 by running " npm i web3@1.0.0-beta.37 " and also .35, but in either case it gave me the same error, although according to this thread it should have helped: https://github.com/ethereum/web3.js/issues/2270
I think if the instructions used the exact package versions and not the latest, then these problems could have been avoided.  Any help is very appreciated.
Thank you!

**Comment by WhaleChen** [comment]
https://github.com/ethereum/web3.js/pull/2317  the bug has already fixed and @yennieb @jaymod may update auroradao. Many 3x
