### ISSUE TITLE
Frequent "STAKING OFFLINE: Internal server error"

### ISSUE THREAD

**Issue by Bobface** [AuroraDAO/aurad#3]
I noticed "STAKING OFFLINE: Internal server error" from time to time in the logs (every hour or so). It seems to get more frequent now. This is my current output:

![err](https://user-images.githubusercontent.com/10945014/51092467-05b92b80-1798-11e9-9fb6-ac95b58670f4.png)

**Comment by Swader** [comment]
Since the credits are applied for every 5 minutes of uptime and from what I can see, everyone's server has intermittent OFFLINE status, this would mean the 5-minute credit intervals are being discarded for all of us. 

This is worrying.

**Comment by bradennapier** [comment]
I wouldn’t worry, we will definitely look into this and take care of it!

**Comment by yennieb** [comment]
Currently the aurad client updates staking status more frequently than strictly required to keep your staking window open, which at least partially mitigates this issue. That said, we are looking at the `Internal server error` to make sure it goes away.

**Comment by yennieb** [comment]
Fixed in today's server update. Please report any further issues!

**Comment by Swader** [comment]
Does this mean another aurad update is coming, or is this the server our nodes talk to?

**Comment by Bobface** [comment]
@Swader The server which the nodes talk to has been fixed. My uptime is now ~99.5%

**Comment by Swader** [comment]
Agreed, uptime is much higher, thanks!
