### ISSUE TITLE
New parity version

### ISSUE THREAD

**Issue by leshacat** [AuroraDAO/aurad#51]
Hi,

There are newer parity versions, considering the current one does not work and gives manifest error, why not upgrade parity?

https://github.com/AuroraDAO/aurad/issues/50

https://github.com/paritytech/parity-ethereum/releases

Thanks

**Comment by yennieb** [comment]
@leshacat thanks, we are planning to upgrade in the next release. Unfortunately parity unexpectedly pulled every version tag from DockerHub except for 2.5.0 (beta) and 2.3.3 (not even the latest 2.3.x), but we are working with them on a solution ASAP.

**Comment by Summonerrk** [comment]
I have issue with a parity
https://i.imgur.com/zvu28xb.png

How can I resolve this problem?

**Comment by leshacat** [comment]
@yennieb 

I posted a fix here the other day, works good with parity 2.5.0

https://github.com/AuroraDAO/aurad/issues/50

**Comment by chkiss** [comment]
Update to the latest version, there's an official fix.
