### ISSUE TITLE
STAKING OFFLINE: undefined

### ISSUE THREAD

**Issue by Bobface** [AuroraDAO/aurad#8]
Another, though not-so-frequent, staking error message:

```
17:24:36 0|worker  | STAKING OFFLINE: undefined
17:25:06 0|worker  | STAKING OFFLINE: undefined
17:25:18 0|worker  | STAKING ONLINE: In rotation
17:25:22 0|worker  | STAKING OFFLINE: Internal server error
17:25:37 0|worker  | STAKING ONLINE: In rotation
```

**Comment by yennieb** [comment]
@Bobface thanks! We just deployed a fix for the "internal server error" related to our DNS service limits. Closing for now but please reopen if you continue to see that.
